import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'package:terminice/testing.dart';

typedef DemoRunner = FutureOr<void> Function(
  Terminice terminice,
  Directory sampleProject,
);

void main(List<String> args) async {
  final scriptDir = File.fromUri(Platform.script).parent;
  final outputFile =
      args.isNotEmpty ? File(args.first) : File('${scriptDir.path}/frames.js');
  final relativeSampleProject =
      Directory('terminice_visual_demo/sample_project');
  final sampleProject = relativeSampleProject.existsSync()
      ? relativeSampleProject
      : Directory('${scriptDir.path}/sample_project');
  final frames = <Map<String, Object?>>[];

  for (var componentIndex = 0;
      componentIndex < _components.length;
      componentIndex++) {
    final component = _components[componentIndex];
    for (var themeIndex = 0; themeIndex < _themes.length; themeIndex++) {
      final theme = _themes[themeIndex];
      final display =
          _displays[(componentIndex + themeIndex) % _displays.length];
      frames.add(
        await _captureFrame(
          component: component,
          theme: theme,
          display: display,
          sampleProject: sampleProject,
        ),
      );
    }
  }

  final payload = <String, Object?>{
    'kind': 'terminice-real-terminal-frames',
    'source':
        'Generated by terminice_visual_demo/generate.dart from real Terminice output.',
    'components': _components.length,
    'themes': _themes.map((theme) => theme.id).toList(growable: false),
    'frames': frames,
  };

  final json = const JsonEncoder.withIndent('  ').convert(payload);
  outputFile.writeAsStringSync(
    'globalThis.TERMINICE_REAL_DEMO = $json;\n'
    'globalThis.TERMINICE_REAL_FRAMES = globalThis.TERMINICE_REAL_DEMO.frames;\n',
  );

  stdout.writeln(
      'Generated ${frames.length} real terminal frames: ${outputFile.path}');
}

Future<Map<String, Object?>> _captureFrame({
  required DemoComponent component,
  required DemoTheme theme,
  required String display,
  required Directory sampleProject,
}) async {
  final base = _applyDisplay(_applyTheme(Terminice(), theme.id), display);
  final tester = TerminiceTester.interactive(
    base: base,
    script: _scriptForComponent(component, theme.id),
    columns: 96,
    rows: 32,
  );

  await tester.runAsync((terminice) async {
    await Future<void>.sync(() => component.run(terminice, sampleProject));
  });

  final raw = tester.output.raw;
  final screen = TerminalScreenCapture.fromAnsi(raw);

  return <String, Object?>{
    'id': component.id,
    'group': component.group,
    'summary': component.summary,
    'code': component.code,
    'theme': theme.id,
    'display': display,
    'chain': 't.${theme.id}.$display',
    'html': screen.html,
    'plainText': screen.plainText,
    'containsAnsi': tester.output.containsAnsiControls,
  };
}

TerminalScript? _scriptForComponent(DemoComponent component, String themeId) {
  if (component.id == 'themeDemo') {
    return _themeDemoScript(themeId);
  }

  return component.script;
}

TerminalScript _themeDemoScript(String themeId) {
  const themeOrder = [
    'dark',
    'matrix',
    'fire',
    'pastel',
    'ocean',
    'monochrome',
    'neon',
    'arcane',
    'phantom',
  ];
  final index = themeOrder.indexOf(themeId).clamp(0, themeOrder.length - 1);

  return TerminalScript([
    for (var i = 0; i < index; i++)
      TerminalScriptStep.key(KeyEventType.arrowDown),
    TerminalScriptStep.key(KeyEventType.esc),
  ]);
}

Terminice _applyTheme(Terminice terminice, String theme) {
  return switch (theme) {
    'dark' => terminice.dark,
    'matrix' => terminice.matrix,
    'fire' => terminice.fire,
    'pastel' => terminice.pastel,
    'ocean' => terminice.ocean,
    'monochrome' => terminice.monochrome,
    'neon' => terminice.neon,
    'arcane' => terminice.arcane,
    'phantom' => terminice.phantom,
    _ => terminice,
  };
}

String _themeIdFor(dynamic theme) {
  final colors = theme.colors as dynamic;
  final accent = colors.accent as String;
  final selection = colors.selection as String;

  if (accent == '\x1B[32m' && selection == '\x1B[32m') return 'matrix';
  if (accent == '\x1B[31m' && selection == '\x1B[31m') return 'fire';
  if (accent == '\x1B[95m' && selection == '\x1B[94m') return 'pastel';
  if (accent == '\x1B[94m' && selection == '\x1B[34m') return 'ocean';
  if (accent == '\x1B[97m' && selection == '\x1B[37m') return 'monochrome';
  if (accent == '\x1B[95m' && selection == '\x1B[93m') return 'neon';
  if (accent == '\x1B[38;5;141m' && selection == '\x1B[38;5;99m') {
    return 'arcane';
  }
  if (accent == '\x1B[38;5;103m' && selection == '\x1B[38;5;60m') {
    return 'phantom';
  }
  return 'dark';
}

Terminice _applyDisplay(Terminice terminice, String display) {
  return switch (display) {
    'compact' => terminice.compact,
    'minimal' => terminice.minimal,
    _ => terminice.verbose,
  };
}

class DemoTheme {
  final String id;

  const DemoTheme(this.id);
}

class DemoComponent {
  final String id;
  final String group;
  final String summary;
  final String code;
  final TerminalScript? script;
  final DemoRunner run;

  const DemoComponent({
    required this.id,
    required this.group,
    required this.summary,
    required this.code,
    required this.run,
    this.script,
  });
}

const _themes = <DemoTheme>[
  DemoTheme('dark'),
  DemoTheme('matrix'),
  DemoTheme('fire'),
  DemoTheme('pastel'),
  DemoTheme('ocean'),
  DemoTheme('monochrome'),
  DemoTheme('neon'),
  DemoTheme('arcane'),
  DemoTheme('phantom'),
];

const _displays = <String>['compact'];

final _components = <DemoComponent>[
  DemoComponent(
    id: 'text',
    group: 'Prompts',
    summary: 'Single-line terminal input.',
    code: "final name = t.text('Project name');",
    script: TerminalScript([
      TerminalScriptStep.text('terminice_app'),
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, _) => t.text('Project name', placeholder: 'my_cli'),
  ),
  DemoComponent(
    id: 'password',
    group: 'Prompts',
    summary: 'Masked secure input.',
    code: "final token = t.password('API token');",
    script: TerminalScript([
      TerminalScriptStep.text('super-secret'),
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, _) => t.password('API token', maskChar: '*'),
  ),
  DemoComponent(
    id: 'confirm',
    group: 'Prompts',
    summary: 'Clear yes/no confirmation.',
    code: "final publish = t.confirm(message: 'Publish package?');",
    script: TerminalScript([
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, _) => t.confirm(message: 'Publish package?'),
  ),
  DemoComponent(
    id: 'multiline',
    group: 'Prompts',
    summary: 'Small terminal text editor.',
    code: "final notes = t.multiline('Release notes');",
    script: TerminalScript([
      TerminalScriptStep.text('Add visual demo'),
      TerminalScriptStep.key(KeyEventType.enter),
      TerminalScriptStep.text('Ship cleaner docs'),
      TerminalScriptStep.key(KeyEventType.ctrlD),
    ]),
    run: (t, _) => t.multiline('Release notes', visibleLines: 4),
  ),
  DemoComponent(
    id: 'slider',
    group: 'Prompts',
    summary: 'Numeric selection on one axis.',
    code: "final volume = t.slider('Volume', initial: 70);",
    script: TerminalScript([
      TerminalScriptStep.key(KeyEventType.arrowRight),
      TerminalScriptStep.key(KeyEventType.arrowRight),
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, _) => t.slider('Volume', initial: 70, step: 5, showPercent: true),
  ),
  DemoComponent(
    id: 'range',
    group: 'Prompts',
    summary: 'Dual-value min/max selection.',
    code: "final range = t.range('Port range');",
    script: TerminalScript([
      TerminalScriptStep.key(KeyEventType.arrowRight),
      TerminalScriptStep.key(KeyEventType.arrowDown),
      TerminalScriptStep.key(KeyEventType.arrowLeft),
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, _) => t.range(
      'Port range',
      min: 3000,
      max: 9000,
      startInitial: 4200,
      endInitial: 7600,
      unit: '',
    ),
  ),
  DemoComponent(
    id: 'rating',
    group: 'Prompts',
    summary: 'Fast rating input.',
    code: "final score = t.rating('DX score');",
    script: TerminalScript([
      TerminalScriptStep.key(KeyEventType.arrowRight),
      TerminalScriptStep.key(KeyEventType.arrowRight),
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, _) => t.rating(
      'DX score',
      initial: 3,
      labels: const ['Rough', 'Okay', 'Good', 'Great', 'Excellent'],
    ),
  ),
  DemoComponent(
    id: 'date',
    group: 'Prompts',
    summary: 'Keyboard-friendly date input.',
    code: "final date = t.date('Release date');",
    script: TerminalScript([
      TerminalScriptStep.key(KeyEventType.arrowRight),
      TerminalScriptStep.key(KeyEventType.arrowDown),
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, _) => t.date('Release date', initial: DateTime(2026, 7, 5)),
  ),
  DemoComponent(
    id: 'form',
    group: 'Prompts',
    summary: 'Multiple fields in one prompt.',
    code: "final project = t.form('New project', fields: fields);",
    script: TerminalScript([
      TerminalScriptStep.text('terminice_app'),
      TerminalScriptStep.key(KeyEventType.tab),
      TerminalScriptStep.text('CLI'),
      TerminalScriptStep.key(KeyEventType.tab),
      TerminalScriptStep.text('MIT'),
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, _) => t.form(
      'New project',
      fields: const [
        FormFieldConfig(label: 'Name', placeholder: 'my_cli', required: true),
        FormFieldConfig(label: 'Template', placeholder: 'CLI'),
        FormFieldConfig(label: 'License', placeholder: 'MIT'),
      ],
    ),
  ),
  DemoComponent(
    id: 'searchSelector',
    group: 'Selectors',
    summary: 'Filterable option list.',
    code:
        "final template = t.searchSelector(prompt: 'Template', options: templates);",
    script: TerminalScript([
      TerminalScriptStep.text('cl'),
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, _) => t.searchSelector(
      prompt: 'Template',
      showSearch: true,
      options: const [
        'CLI app',
        'Clean architecture',
        'Cloud worker',
        'Class library',
        'Server app',
        'Package',
      ],
    ),
  ),
  DemoComponent(
    id: 'choiceSelector',
    group: 'Selectors',
    summary: 'Card-style choices.',
    code: "final stack = t.choiceSelector('Choose stack', items: stacks);",
    script: TerminalScript([
      TerminalScriptStep.key(KeyEventType.arrowRight),
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, _) => t.choiceSelector(
      'Choose stack',
      items: const [
        ChoiceItem('CLI', subtitle: 'Command apps'),
        ChoiceItem('Server', subtitle: 'APIs'),
        ChoiceItem('Package', subtitle: 'Libraries'),
        ChoiceItem('Automation', subtitle: 'Scripts'),
      ],
    ),
  ),
  DemoComponent(
    id: 'checkboxSelector',
    group: 'Selectors',
    summary: 'Multi-select checklist.',
    code: "final features = t.checkboxSelector('Features', options: features);",
    script: TerminalScript([
      TerminalScriptStep.key(KeyEventType.space),
      TerminalScriptStep.key(KeyEventType.arrowDown),
      TerminalScriptStep.key(KeyEventType.space),
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, _) => t.checkboxSelector(
      'Features',
      options: const ['Git', 'CI', 'Docker', 'Examples'],
    ),
  ),
  DemoComponent(
    id: 'gridSelector',
    group: 'Selectors',
    summary: 'Two-dimensional navigation.',
    code:
        "final target = t.gridSelector(prompt: 'Deploy target', options: targets);",
    script: TerminalScript([
      TerminalScriptStep.key(KeyEventType.arrowRight),
      TerminalScriptStep.key(KeyEventType.arrowDown),
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, _) => t.gridSelector(
      prompt: 'Deploy target',
      columns: 3,
      options: const ['US East', 'US West', 'EU', 'Asia', 'Local', 'Preview'],
    ),
  ),
  DemoComponent(
    id: 'tagSelector',
    group: 'Selectors',
    summary: 'Chip-style multi-select.',
    code: "final labels = t.tagSelector(prompt: 'Labels', tags: labels);",
    script: TerminalScript([
      TerminalScriptStep.key(KeyEventType.space),
      TerminalScriptStep.key(KeyEventType.arrowRight),
      TerminalScriptStep.key(KeyEventType.space),
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, _) => t.tagSelector(
      prompt: 'Labels',
      tags: const ['stable', 'docs', 'cli', 'theme', 'tests', 'release'],
      maxContentWidth: 34,
    ),
  ),
  DemoComponent(
    id: 'toggleGroup',
    group: 'Selectors',
    summary: 'Multiple boolean switches.',
    code: "final flags = t.toggleGroup('Options', items: toggles);",
    script: TerminalScript([
      TerminalScriptStep.key(KeyEventType.space),
      TerminalScriptStep.key(KeyEventType.arrowDown),
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, _) => t.toggleGroup(
      'Options',
      items: const [
        ToggleItem('CI fallback', initialOn: true),
        ToggleItem('Snapshots', initialOn: true),
        ToggleItem('Verbose logs'),
      ],
    ),
  ),
  DemoComponent(
    id: 'commandPalette',
    group: 'Selectors',
    summary: 'Fuzzy command launcher.',
    code: "final command = t.commandPalette('Command', commands: commands);",
    script: TerminalScript([
      TerminalScriptStep.text('pub'),
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, _) => t.commandPalette(
      'Command',
      commands: const [
        CommandEntry(id: 'get', title: 'pub get', subtitle: 'Install packages'),
        CommandEntry(id: 'publish', title: 'pub publish', subtitle: 'Release'),
        CommandEntry(id: 'test', title: 'test', subtitle: 'Run suite'),
      ],
    ),
  ),
  DemoComponent(
    id: 'filePicker',
    group: 'Pickers',
    summary: 'Searchable file browser.',
    code: "final file = t.filePicker('Choose file');",
    script: TerminalScript([
      TerminalScriptStep.text('cli'),
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, sample) => t.filePicker('Choose file', startDirectory: sample),
  ),
  DemoComponent(
    id: 'pathPicker',
    group: 'Pickers',
    summary: 'Directory and path selection.',
    code: "final folder = t.pathPicker('Output folder');",
    script: TerminalScript([
      TerminalScriptStep.key(KeyEventType.arrowDown),
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, sample) => t.pathPicker('Output folder', startDirectory: sample),
  ),
  DemoComponent(
    id: 'colorPicker',
    group: 'Pickers',
    summary: 'ANSI color selection.',
    code: "final color = t.colorPicker('Accent color');",
    script: TerminalScript([
      TerminalScriptStep.key(KeyEventType.arrowRight),
      TerminalScriptStep.key(KeyEventType.arrowRight),
      TerminalScriptStep.key(KeyEventType.arrowDown),
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, _) =>
        t.colorPicker('Accent color', initialHex: '#22C55E', cols: 12, rows: 5),
  ),
  DemoComponent(
    id: 'datePicker',
    group: 'Pickers',
    summary: 'Calendar-based date selection.',
    code: "final launch = t.datePicker('Launch day');",
    script: TerminalScript([
      TerminalScriptStep.key(KeyEventType.arrowRight),
      TerminalScriptStep.key(KeyEventType.arrowDown),
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, _) =>
        t.datePicker('Launch day', initialDate: DateTime(2026, 7, 5)),
  ),
  DemoComponent(
    id: 'loadingSpinner',
    group: 'Indicators',
    summary: 'Framed loading animation.',
    code: "t.loadingSpinner('Installing').show(2);",
    run: (t, _) =>
        t.loadingSpinner('Installing', message: 'Resolving packages').show(2),
  ),
  DemoComponent(
    id: 'inlineSpinner',
    group: 'Indicators',
    summary: 'One-line loading status.',
    code: "t.inlineSpinner('Syncing').show(1);",
    run: (t, _) => t.inlineSpinner('Syncing workspace').show(1),
  ),
  DemoComponent(
    id: 'progressBar',
    group: 'Indicators',
    summary: 'Determinate progress frame.',
    code: "t.progressBar('Uploading').show(current: 68, total: 100);",
    run: (t, _) => t.progressBar('Uploading').show(current: 68, total: 100),
  ),
  DemoComponent(
    id: 'inlineProgressBar',
    group: 'Indicators',
    summary: 'Compact progress line.',
    code: "t.inlineProgressBar('Build').show(current: 68, total: 100);",
    run: (t, _) => t.inlineProgressBar('Build').show(current: 68, total: 100),
  ),
  DemoComponent(
    id: 'progressDots',
    group: 'Indicators',
    summary: 'Minimal dot progress.',
    code: "t.progressDots('Waiting for server').show(phase: 2);",
    run: (t, _) => ProgressDots(
      'Waiting for server',
      message: 'checking health',
      theme: t.defaultTheme,
    ).show(phase: 2),
  ),
  DemoComponent(
    id: 'messagePrimitives',
    group: 'Workflow & CLI UX',
    summary: 'Small polished status lines.',
    code:
        "t.info('Reading config');\nt.success('Published');\nt.warn('Using cache');",
    run: (t, _) {
      t.info('Reading config');
      t.success('Published');
      t.warn('Using cache');
      t.detail('terminice/visual_demo');
    },
  ),
  DemoComponent(
    id: 'task',
    group: 'Workflow & CLI UX',
    summary: 'Async status wrapper.',
    code: "await t.task('Publishing', run: publish);",
    run: (t, _) async => t.task<void>(
      'Publishing',
      message: 'running checks',
      success: 'Published',
      run: () async => Future<void>.delayed(const Duration(milliseconds: 6)),
    ),
  ),
  DemoComponent(
    id: 'progressTask',
    group: 'Workflow & CLI UX',
    summary: 'Async progress wrapper.',
    code: "await t.progressTask('Uploading', total: 4, run: upload);",
    run: (t, _) async => t.progressTask<void>(
      'Uploading',
      total: 4,
      message: 'starting',
      success: 'Uploaded',
      run: (progress) async {
        progress.update(current: 2, message: '2 / 4 files');
        await Future<void>.delayed(const Duration(milliseconds: 6));
        progress.update(current: 4, message: '4 / 4 files');
      },
    ),
  ),
  DemoComponent(
    id: 'trackStream',
    group: 'Workflow & CLI UX',
    summary: 'Stream collection with progress.',
    code: "final files = await t.trackStream('Scanning', stream, total: 4);",
    run: (t, _) async => t.trackStream<int>(
      'Scanning',
      Stream<int>.fromIterable([1, 2, 3, 4]),
      total: 4,
      success: 'Scan complete',
    ),
  ),
  DemoComponent(
    id: 'TaskProgress',
    group: 'Workflow & CLI UX',
    summary: 'Mutable task progress state.',
    code: "progress.update(current: 3, message: 'Almost done');",
    run: (t, _) => _showUtilityFrame(
      t,
      'TaskProgress',
      ['current: 3', 'total: 4', 'message: Almost done'],
    ),
  ),
  DemoComponent(
    id: 'TaskDisplay',
    group: 'Workflow & CLI UX',
    summary: 'Task rendering mode.',
    code: "await t.task('Deploy', display: TaskDisplay.inline, run: deploy);",
    run: (t, _) => _showUtilityFrame(
      t,
      'TaskDisplay',
      ['auto: best terminal mode', 'inline: animated line', 'plain: CI safe'],
    ),
  ),
  DemoComponent(
    id: 'TaskFinalBehavior',
    group: 'Workflow & CLI UX',
    summary: 'Final output policy.',
    code: "await t.task('Deploy', finalBehavior: TaskFinalBehavior.persist);",
    run: (t, _) => _showUtilityFrame(
      t,
      'TaskFinalBehavior',
      ['persist: keep status', 'clear: leave clean output'],
    ),
  ),
  DemoComponent(
    id: 'flow',
    group: 'Workflow & CLI UX',
    summary: 'Sequential setup composition.',
    code:
        "final result = t.flow('New project')\n  .text('name', 'Name')\n  .select('template', 'Template', options: templates)\n  .review()\n  .run();",
    script: TerminalScript([
      TerminalScriptStep.text('terminice_app'),
      TerminalScriptStep.key(KeyEventType.enter),
      TerminalScriptStep.key(KeyEventType.enter),
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, _) => t
        .flow('New project')
        .progress()
        .text('name', 'Name', placeholder: 'my_cli')
        .select('template', 'Template',
            options: const ['CLI', 'Server', 'Package'])
        .review()
        .run(),
  ),
  DemoComponent(
    id: 'customComponents',
    group: 'Workflow & CLI UX',
    summary: 'Reusable custom Terminice UI.',
    code: "final value = t.runComponent(MyPicker());",
    run: (t, _) => t.runComponent(
      TerminiceComponent<String>.from((context) {
        return context.withActiveTerminal(() {
          final out = RenderOutput();
          FrameView(title: 'Brand picker', theme: context.theme).showTo(out,
              (ctx) {
            ctx.gutterLine(
                '${context.theme.accent}theme${context.theme.reset}: inherited');
            ctx.gutterLine(
                '${context.theme.accent}fallback${context.theme.reset}: inherited');
            ctx.gutterLine(
                '${context.theme.accent}testing${context.theme.reset}: inherited');
          });
          return 'custom';
        });
      }),
    ),
  ),
  DemoComponent(
    id: 'configEditor',
    group: 'Configuration & Guides',
    summary: 'Nested settings editor.',
    code: "final result = t.configEditor('Settings', fields: config);",
    script: TerminalScript([
      TerminalScriptStep.key(KeyEventType.esc),
    ]),
    run: (t, _) => t.configEditor(
      'Settings',
      fields: [
        ThemeConfigurable(
          key: 'theme',
          label: 'Theme',
          value: _themeIdFor(t.defaultTheme),
        ),
        BoolConfigurable(key: 'ci', label: 'CI fallback', value: true),
        NumberConfigurable(
            key: 'retries', label: 'Retries', value: 3, min: 0, max: 9),
        GroupConfigurable(
          key: 'docs',
          label: 'Docs',
          children: [
            StringConfigurable(key: 'path', label: 'Path', value: 'README.md'),
          ],
        ),
      ],
    ),
  ),
  DemoComponent(
    id: 'cheatSheet',
    group: 'Configuration & Guides',
    summary: 'Framed reference table.',
    code: "t.cheatSheet('Shortcuts', entries: rows);",
    run: (t, _) => t.cheatSheet(
      'Shortcuts',
      columns: const ['Key', 'Action', 'Where'],
      entries: const [
        ['Enter', 'Confirm', 'Prompts'],
        ['Space', 'Toggle', 'Selectors'],
        ['Esc', 'Cancel', 'Everywhere'],
      ],
    ),
  ),
  DemoComponent(
    id: 'helpCenter',
    group: 'Configuration & Guides',
    summary: 'Searchable help browser.',
    code: "final doc = t.helpCenter(docs: docs);",
    script: TerminalScript([
      TerminalScriptStep.text('theme'),
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, _) => t.helpCenter(
      docs: const [
        HelpDoc(
          id: 'themes',
          title: 'Themes',
          category: 'Styling',
          content: 'Every component inherits the same Terminice theme.',
        ),
        HelpDoc(
          id: 'tests',
          title: 'Testing',
          category: 'Quality',
          content: 'Use TerminiceTester to script input and inspect output.',
        ),
      ],
    ),
  ),
  DemoComponent(
    id: 'hotkeyGuide',
    group: 'Configuration & Guides',
    summary: 'Interactive shortcut guide.',
    code: "t.hotkeyGuide(title: 'Keyboard controls', shortcuts: shortcuts);",
    script: TerminalScript([
      TerminalScriptStep.key(KeyEventType.enter),
    ]),
    run: (t, _) => t.hotkeyGuide(
      title: 'Keyboard controls',
      shortcuts: const [
        ['Arrows', 'Move focus'],
        ['Space', 'Toggle item'],
        ['Ctrl+C', 'Cancel'],
      ],
    ),
  ),
  DemoComponent(
    id: 'themeDemo',
    group: 'Configuration & Guides',
    summary: 'Interactive theme gallery.',
    code: "t.themeDemo();",
    run: (t, _) => t.themeDemo(),
  ),
];

void _showUtilityFrame(Terminice t, String title, List<String> rows) {
  t.runWithComponent<void>((context) {
    context.withActiveTerminal<void>(() {
      final out = RenderOutput();
      FrameView(title: title, theme: context.theme).showTo(out, (ctx) {
        for (final row in rows) {
          ctx.gutterLine(row);
        }
      });
    });
  });
}

class TerminalScreenCapture {
  final String html;
  final String plainText;

  const TerminalScreenCapture({
    required this.html,
    required this.plainText,
  });

  factory TerminalScreenCapture.fromAnsi(String raw) {
    final emulator = _TerminalEmulator();
    emulator.write(raw);
    return TerminalScreenCapture(
      html: emulator.bestHtml,
      plainText: emulator.bestPlainText,
    );
  }
}

class _TerminalEmulator {
  final List<List<_StyledRun>> _lines = <List<_StyledRun>>[<_StyledRun>[]];
  final _htmlEscape = const HtmlEscape(HtmlEscapeMode.element);

  _AnsiStyle _style = const _AnsiStyle();
  int _row = 0;
  String _bestHtml = '<pre class="terminal-pre"></pre>';
  String _bestPlainText = '';

  String get bestHtml => _bestHtml;

  String get bestPlainText => _bestPlainText;

  void write(String raw) {
    for (var i = 0; i < raw.length; i++) {
      final code = raw.codeUnitAt(i);
      if (code == 0x1B && i + 1 < raw.length) {
        if (raw.codeUnitAt(i + 1) == 0x5B) {
          final end = _findCsiEnd(raw, i + 2);
          if (end != -1) {
            _handleCsi(raw.substring(i + 2, end), raw[end]);
            i = end;
            _rememberVisibleScreen();
            continue;
          }
        }
        continue;
      }

      switch (code) {
        case 0x0A:
          _newline();
          break;
        case 0x0D:
          break;
        case 0x08:
        case 0x7F:
          break;
        default:
          if (code >= 0x20 || raw[i].trim().isNotEmpty) {
            _append(raw[i]);
          }
      }
      _rememberVisibleScreen();
    }
  }

  int _findCsiEnd(String raw, int start) {
    for (var i = start; i < raw.length; i++) {
      final code = raw.codeUnitAt(i);
      if (code >= 0x40 && code <= 0x7E) return i;
    }
    return -1;
  }

  void _handleCsi(String params, String finalChar) {
    switch (finalChar) {
      case 'm':
        _applySgr(params);
        break;
      case 'A':
        final amount = _firstInt(params) ?? 1;
        _row = math.max(0, _row - amount);
        break;
      case 'J':
        if (_row < _lines.length) {
          _lines.removeRange(_row, _lines.length);
        }
        if (_lines.isEmpty) _lines.add(<_StyledRun>[]);
        _row = math.min(_row, _lines.length - 1);
        break;
      case 'K':
        _ensureRow();
        _lines[_row].clear();
        break;
      case 'H':
      case 'f':
        _row = 0;
        _ensureRow();
        break;
      default:
        break;
    }
  }

  void _applySgr(String params) {
    final values = params.isEmpty
        ? <int>[0]
        : params.split(';').map((part) => int.tryParse(part) ?? -1).toList();

    for (var i = 0; i < values.length; i++) {
      final code = values[i];
      switch (code) {
        case 0:
          _style = const _AnsiStyle();
          break;
        case 1:
          _style = _style.copyWith(bold: true);
          break;
        case 2:
          _style = _style.copyWith(dim: true);
          break;
        case 4:
          _style = _style.copyWith(underline: true);
          break;
        case 7:
          _style = _style.copyWith(inverse: true);
          break;
        case 22:
          _style = _style.copyWith(bold: false, dim: false);
          break;
        case 24:
          _style = _style.copyWith(underline: false);
          break;
        case 27:
          _style = _style.copyWith(inverse: false);
          break;
        case 39:
          _style = _style.copyWith(clearForeground: true);
          break;
        case 49:
          _style = _style.copyWith(clearBackground: true);
          break;
        case 38:
        case 48:
          if (i + 2 < values.length && values[i + 1] == 5) {
            final color = _ansi256(values[i + 2]);
            _style = code == 38
                ? _style.copyWith(foreground: color)
                : _style.copyWith(background: color);
            i += 2;
          } else if (i + 4 < values.length && values[i + 1] == 2) {
            final color = _rgb(values[i + 2], values[i + 3], values[i + 4]);
            _style = code == 38
                ? _style.copyWith(foreground: color)
                : _style.copyWith(background: color);
            i += 4;
          }
          break;
        default:
          final color = _ansiBasic(code);
          if (color != null) {
            if ((code >= 40 && code <= 47) || (code >= 100 && code <= 107)) {
              _style = _style.copyWith(background: color);
            } else {
              _style = _style.copyWith(foreground: color);
            }
          }
      }
    }
  }

  int? _firstInt(String value) {
    final match = RegExp(r'\d+').firstMatch(value);
    return match == null ? null : int.tryParse(match.group(0)!);
  }

  void _newline() {
    _row += 1;
    _ensureRow();
  }

  void _append(String text) {
    _ensureRow();
    final line = _lines[_row];
    if (line.isNotEmpty && line.last.style == _style) {
      line.last.append(text);
      return;
    }
    line.add(_StyledRun(_style, text));
  }

  void _ensureRow() {
    while (_lines.length <= _row) {
      _lines.add(<_StyledRun>[]);
    }
  }

  void _rememberVisibleScreen() {
    final plain = _plainText().trimRight();
    if (plain.trim().isEmpty) return;
    _bestPlainText = plain;
    _bestHtml = '<pre class="terminal-pre">${_toHtml()}</pre>';
  }

  String _plainText() {
    return _lines.map((line) => line.map((run) => run.text).join()).join('\n');
  }

  String _toHtml() {
    final htmlLines = _lines.map((line) {
      return line.map((run) {
        final escaped = _htmlEscape.convert(run.text);
        final css = run.style.css;
        if (css.isEmpty) return escaped;
        return '<span style="$css">$escaped</span>';
      }).join();
    }).toList();

    while (htmlLines.isNotEmpty && htmlLines.last.trim().isEmpty) {
      htmlLines.removeLast();
    }

    return htmlLines.join('\n');
  }
}

class _StyledRun {
  final _AnsiStyle style;
  final StringBuffer _text;

  _StyledRun(this.style, String text) : _text = StringBuffer(text);

  String get text => _text.toString();

  void append(String value) {
    _text.write(value);
  }
}

class _AnsiStyle {
  final String? foreground;
  final String? background;
  final bool bold;
  final bool dim;
  final bool underline;
  final bool inverse;

  const _AnsiStyle({
    this.foreground,
    this.background,
    this.bold = false,
    this.dim = false,
    this.underline = false,
    this.inverse = false,
  });

  _AnsiStyle copyWith({
    String? foreground,
    String? background,
    bool? bold,
    bool? dim,
    bool? underline,
    bool? inverse,
    bool clearForeground = false,
    bool clearBackground = false,
  }) {
    return _AnsiStyle(
      foreground: clearForeground ? null : foreground ?? this.foreground,
      background: clearBackground ? null : background ?? this.background,
      bold: bold ?? this.bold,
      dim: dim ?? this.dim,
      underline: underline ?? this.underline,
      inverse: inverse ?? this.inverse,
    );
  }

  String get css {
    final styles = <String>[];
    var fg = foreground;
    var bg = background;

    if (inverse) {
      final previousFg = fg;
      fg = bg ?? '#08111f';
      bg = previousFg ?? 'rgba(245,247,251,0.9)';
    }

    if (fg != null) styles.add('color:$fg');
    if (bg != null) styles.add('background-color:$bg');
    if (bold) styles.add('font-weight:800');
    if (dim) styles.add('opacity:.62');
    if (underline) styles.add('text-decoration:underline');
    if (inverse) styles.add('border-radius:3px');
    if (inverse) styles.add('padding:0 1px');
    return styles.join(';');
  }

  @override
  bool operator ==(Object other) {
    return other is _AnsiStyle &&
        other.foreground == foreground &&
        other.background == background &&
        other.bold == bold &&
        other.dim == dim &&
        other.underline == underline &&
        other.inverse == inverse;
  }

  @override
  int get hashCode => Object.hash(
        foreground,
        background,
        bold,
        dim,
        underline,
        inverse,
      );
}

String? _ansiBasic(int code) {
  const normal = <int, String>{
    30: '#111827',
    31: '#ef4444',
    32: '#22c55e',
    33: '#eab308',
    34: '#3b82f6',
    35: '#d946ef',
    36: '#06b6d4',
    37: '#e5e7eb',
    90: '#6b7280',
    91: '#f87171',
    92: '#4ade80',
    93: '#facc15',
    94: '#60a5fa',
    95: '#e879f9',
    96: '#22d3ee',
    97: '#f9fafb',
  };

  if (normal.containsKey(code)) return normal[code];
  if (code >= 40 && code <= 47) return normal[code - 10];
  if (code >= 100 && code <= 107) return normal[code - 10];
  return null;
}

String _ansi256(int code) {
  if (code < 16) {
    return _ansiBasic(code < 8 ? code + 30 : code + 82) ?? '#f9fafb';
  }
  if (code >= 16 && code <= 231) {
    final index = code - 16;
    const steps = [0, 95, 135, 175, 215, 255];
    final r = steps[index ~/ 36];
    final g = steps[(index % 36) ~/ 6];
    final b = steps[index % 6];
    return _rgb(r, g, b);
  }
  if (code >= 232 && code <= 255) {
    final gray = 8 + (code - 232) * 10;
    return _rgb(gray, gray, gray);
  }
  return '#f9fafb';
}

String _rgb(int r, int g, int b) {
  String hex(int value) =>
      value.clamp(0, 255).toRadixString(16).padLeft(2, '0');
  return '#${hex(r)}${hex(g)}${hex(b)}';
}
