import 'dart:convert';
import 'dart:io';

const _unicodeVersion = '15.1.0';
const _unicodeRoot = 'https://www.unicode.org/Public/$_unicodeVersion/ucd';
const _sources = <String, String>{
  'EastAsianWidth.txt': '$_unicodeRoot/EastAsianWidth.txt',
  'emoji-data.txt': '$_unicodeRoot/emoji/emoji-data.txt',
  'emoji-variation-sequences.txt':
      '$_unicodeRoot/emoji/emoji-variation-sequences.txt',
  'DerivedGeneralCategory.txt':
      '$_unicodeRoot/extracted/DerivedGeneralCategory.txt',
  'DerivedCoreProperties.txt': '$_unicodeRoot/DerivedCoreProperties.txt',
};

Future<void> main(List<String> arguments) async {
  final check = arguments.contains('--check');
  if (arguments.any((argument) => argument != '--check')) {
    stderr.writeln(
        'Usage: dart run tool/generate_terminal_text_unicode_data.dart [--check]');
    exitCode = 64;
    return;
  }

  final sourceText = <String, String>{};
  for (final source in _sources.entries) {
    sourceText[source.key] = await _download(source.value);
  }

  final wide = _parsePropertyRanges(
    sourceText['EastAsianWidth.txt']!,
    const {'W', 'F'},
  );
  final emojiPresentation = _parsePropertyRanges(
    sourceText['emoji-data.txt']!,
    const {'Emoji_Presentation'},
  );
  final emojiVariationBases = _parseEmojiVariationBases(
    sourceText['emoji-variation-sequences.txt']!,
  );
  final combining = _parsePropertyRanges(
    sourceText['DerivedGeneralCategory.txt']!,
    const {'Mn', 'Me'},
  );
  final defaultIgnorable = _parsePropertyRanges(
    sourceText['DerivedCoreProperties.txt']!,
    const {'Default_Ignorable_Code_Point'},
  );
  final zeroWidth = _mergeRanges([...combining, ...defaultIgnorable]);

  final generated = _render(
    wide: wide,
    emojiPresentation: emojiPresentation,
    emojiVariationBases: emojiVariationBases,
    zeroWidth: zeroWidth,
  );
  final output = File('lib/src/utils/terminal_text_unicode_data.dart');

  if (check) {
    if (!output.existsSync() || output.readAsStringSync() != generated) {
      stderr.writeln('${output.path} is not up to date. Regenerate it.');
      exitCode = 1;
    } else {
      stdout.writeln('${output.path} is up to date.');
    }
    return;
  }

  output.writeAsStringSync(generated);
  stdout.writeln(
    'Generated ${output.path}: '
    '${wide.length} wide, '
    '${emojiPresentation.length} emoji-presentation, '
    '${emojiVariationBases.length} emoji-variation-base, '
    '${zeroWidth.length} zero-width ranges.',
  );
}

Future<String> _download(String url) async {
  final client = HttpClient();
  try {
    final request = await client.getUrl(Uri.parse(url));
    request.headers
        .set(HttpHeaders.userAgentHeader, 'termistyle-unicode-generator');
    final response = await request.close();
    if (response.statusCode != HttpStatus.ok) {
      throw HttpException('HTTP ${response.statusCode}', uri: Uri.parse(url));
    }
    return await utf8.decoder.bind(response).join();
  } finally {
    client.close();
  }
}

List<_Range> _parsePropertyRanges(String input, Set<String> properties) {
  final result = <_Range>[];
  for (final rawLine in const LineSplitter().convert(input)) {
    final line = rawLine.split('#').first.trim();
    if (line.isEmpty) continue;
    final fields = line.split(';');
    if (fields.length < 2 || !properties.contains(fields[1].trim())) continue;
    result.add(_parseRange(fields[0].trim()));
  }
  return _mergeRanges(result);
}

List<_Range> _parseEmojiVariationBases(String input) {
  final result = <_Range>[];
  for (final rawLine in const LineSplitter().convert(input)) {
    final line = rawLine.split('#').first.trim();
    if (line.isEmpty) continue;
    result.add(_Range(int.parse(line.split(RegExp(r'\s+')).first, radix: 16)));
  }
  return _mergeRanges(result);
}

_Range _parseRange(String value) {
  final bounds = value.split('..');
  return _Range(
    int.parse(bounds.first, radix: 16),
    bounds.length == 1 ? null : int.parse(bounds.last, radix: 16),
  );
}

List<_Range> _mergeRanges(List<_Range> ranges) {
  ranges.sort((a, b) => a.start.compareTo(b.start));
  final merged = <_Range>[];
  for (final range in ranges) {
    if (merged.isEmpty || range.start > merged.last.end + 1) {
      merged.add(_Range(range.start, range.end));
    } else if (range.end > merged.last.end) {
      merged[merged.length - 1] = _Range(merged.last.start, range.end);
    }
  }
  return merged;
}

String _render({
  required List<_Range> wide,
  required List<_Range> emojiPresentation,
  required List<_Range> emojiVariationBases,
  required List<_Range> zeroWidth,
}) {
  final output = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT EDIT BY HAND.')
    ..writeln('// Generated by tool/generate_terminal_text_unicode_data.dart.')
    ..writeln('// Unicode version: $_unicodeVersion')
    ..writeln('// Sources:');
  for (final url in _sources.values) {
    output.writeln('// - $url');
  }
  output
    ..writeln('//')
    ..writeln(
        '// Policy: East Asian Wide/Fullwidth are two cells; Ambiguous is')
    ..writeln(
        '// narrow. Mn/Me and Default_Ignorable_Code_Point are zero-width.')
    ..writeln()
    ..writeln("const terminalTextUnicodeVersion = '$_unicodeVersion';")
    ..writeln();
  _writeRanges(output, 'terminalTextWideRanges', wide);
  _writeRanges(
    output,
    'terminalTextEmojiPresentationRanges',
    emojiPresentation,
  );
  _writeRanges(
    output,
    'terminalTextEmojiVariationBaseRanges',
    emojiVariationBases,
  );
  _writeRanges(output, 'terminalTextZeroWidthRanges', zeroWidth);
  return '${output.toString().trimRight()}\n';
}

void _writeRanges(StringBuffer output, String name, List<_Range> ranges) {
  output
    ..writeln('// ${ranges.length} sorted, disjoint ranges.')
    ..writeln('// dart format off')
    ..writeln('const $name = <int>[');
  for (var i = 0; i < ranges.length; i += 4) {
    final line = ranges.skip(i).take(4).expand((range) => [
          _hex(range.start),
          _hex(range.end),
        ]);
    output.writeln('  ${line.join(', ')},');
  }
  output
    ..writeln('];')
    ..writeln('// dart format on')
    ..writeln();
}

String _hex(int value) => '0x${value.toRadixString(16)}';

class _Range {
  _Range(this.start, [int? end]) : end = end ?? start;

  final int start;
  final int end;
}
